# Workshops 

## redlistr workshop 

The redlistr workshop, held on Tuesday 5 May 2026, delivered an introduction on how to use the R package redlistr for species and ecosystems Red List assessments. The workshop focused on reproducible analysis, practical “recipe-style” coding, and helping participants build independence after training.  

Through guided exercises, participants explored Extent of Occurrence (EOO), Area of Occupancy (AOO) metrics, and change over time together with hands-on exercises following each demo. The workshop showed the degree of ease or difficulty for participants to use the redlistr package and obtain the outputs using its functions. 

  

The workshop was led by Prof. David Keith, Dr. Aniko Toth, and Dr. José R. Ferrer Paris, with contributions from the EIW team, and included 23 participants from the NSW Department of Climate Change, Energy, the Environment and Water (DCCEEW), the Department of Primary Industries and Regional Development (DPIRD), Queensland Cyber Infrastructure Foundation (QCIF), and UNSW. The new release of the redlistr package is available via this GitHub repository.  

## Shaping the Workflow: Co-designing Ecosystem Indicators workshop 

Shaping the Workflow Workshop was held online on Tuesday 19 May. This workshop was a hands-on codesign session bringing together ecologists, data analysts, coders, and software engineers to discuss how ecosystem indicator development can be improved with reproducible workflows (for more info please see our slides). Rather than presenting a finished product, participants were invited to actively test, question, and improve the demo of the workflow’s conceptual elements based on their real-world experience. The insights gathered will help improve the usability, inclusivity, interoperability, and overall adoption of the proposed solution across diverse user communities.  

  

Given the diversity of tools (and the familiarity of the participants to them), skills, and institutional contexts across the community, the workshop focused on how people interact with the workflow: what works, what doesn’t, and what support is needed to make it usable, inclusive, and scalable.   

The online session was led by Dr. Ada Sanchez-Mercado, Dr. José Ferrer Paris, and Liz Stokes (ARDC), with a great team of facilitators from UNSW (Silvia Colombo and Beatta Zarrabi) and QCIF (Abhimanyu Raj Singh). The workshop was attended by 32 participants (PhD students, early, mid and senior career) professionals from twelve institutions from across Australia from the academic (62.5%), government (34.4%), and private sector (3.2%).  

A feedback form filled by the participants after the workshop highlighted an appreciation for the workshop and especially for the interactive Miro board used in the session. The participants expressed the desire for more frequent (but also shorter) workshops to support ongoing progress. Advice and suggestions on time management, advance preparation, and diverse group discussions were taken into account by the team for future workshops. 

 