---
title: "Co-designing Ecosystem Indicators workshop "
subtitle: "Shaping the Workflow, part II"
author: 
 - Ada Sanchez-Mercado
 - José Ferrer Paris
 - Liz Stokes
 - Silvia Colombo 
 - Beatta Zarrabi
 - Abhimanyu Raj Singh
date: 29 Jun 2026
categories: [Requirements]
language: 
  title-block-author-single: "Organiser"
  title-block-author-plural: "Organisers and facilitators"
  title-block-published: "Date"
---

## Context  

On Monday, 29 June 2026, a second co-design workshop was held online. The goal of the workshop was to scope priority ecosystems and indicators, reflect on the reproducibility of past indicator-development workflows, fill urgent knowledge gaps, and identify which ecosystems are most useful for informing current programs and future scalability. The participants of the workshop included a small group of invited researchers (8 participants) from 4 institutions (University of Melbourne, James Cook University, Queensland University of Technology, University of New South Wales). 

 
## Workshop aims  

The primary aims of the workshop were to: 

Understand how easy it is to find data for specific indicators and the main accessibility challenges 

Identify the main risks when handling data and the specific skills for data preparation 

Determine the current barrier for reproducible workflows 

Determine the next steps and assign the right priority  

## Outputs  

The participants highlighted that workflows need structured and step-by-step documentation at every stage. Moreover, effort should focus on creating a registry of data sources with strict metadata standards and legal pathways for sharing data. 

Participants also discussed the challenge of formally gathering expert feedback making the final results scientifically reproducible; for this reason, workflows should include frameworks to collect experts’ consensus within the code. 

Another concern identified by participants, was that many ecosystems have insufficient data, so workflows need to be built to function effectively even when data is scarce. 

Lastly, during the workshop, the need for a modular design was raised, a design that separates ecosystem-specific configurations from reusable workflow logic.  

  